version: "3.2"
services:
  apache:
    build: 
      context: ./apache
    image: ${DOMAINNAME}/apache:2.4
    container_name: ${DOMAINNAME}-apache
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./${HOST_ROOT_DIR}:/var/www/html/
      - ${CUR_DIR}/certbot/letsencrypt/etc/letsencrypt/live/${DOMAINNAME}/cert.pem:/var/imported/ssl/cert.pem
      - ${CUR_DIR}/certbot/letsencrypt/etc/letsencrypt/live/${DOMAINNAME}/privkey.pem:/var/imported/ssl/privkey.pem
      - ${CUR_DIR}/certbot/letsencrypt/etc/letsencrypt/live/${DOMAINNAME}/fullchain.pem:/var/imported/ssl/fullchain.pem
    restart: always
  mariadb:
    image: mariadb:10.3
    container_name: ${DOMAINNAME}-mariadb
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: on-failure
  redis:
      image: redis
      container_name: ${DOMAINNAME}-redis
      restart: always
      networks:
        - backend
  supervisor:
      build: './supervisor/'
      image: ${DOMAINNAME}/supervisor:7.3
      container_name: ${DOMAINNAME}-supervisor
      volumes:
        - ./${HOST_ROOT_DIR}/:/var/www/html/
      ports:
        - "9001:9001"
      depends_on:
        - redis
        - mariadb
      networks:
        - backend
      restart: on-failure
volumes:
  db-volume:
    external: 
      name: ${DOMAINNAME}-faveoDB
  
networks:
  frontend:
    external:
      name: ${DOMAINNAME}-frontend
  backend:
    external:
      name: ${DOMAINNAME}-backend
